apiVersion: v1
kind: ConfigMap
metadata:
  name: apply-setters
  annotations:
    config.kubernetes.io/local-config: "true"
# spell-checker: disable
data:
  # Set to true if the target cluter is GKE Autopilot.
  inference-pool-cluster-is-autopilot: true
  # Set to true if monitoring should be enabled.
  inference-pool-monitoring-enabled: true
  # This sets the name of the InferencePool object, and the prefix for supporting EndpointPicker.
  inference-pool-name: pool-name
  # Override if the inference pool will be deployed to a namespace other than vllm.
  inference-pool-namespace: vllm
