apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: nginx-jwt
  namespace: nginx-ingress
spec:
  provider:
    gcpsm:
      projectID: my-project-id
      auth:
        workloadIdentity:
          clusterLocation: my-cluster-location
          clusterName: my-cluster-name
          serviceAccountRef:
            name: nginx-ingress
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nginx-jwt
  namespace: nginx-ingress
spec:
  refreshInterval: 10m0s
  secretStoreRef:
    name: nginx-jwt
    kind: SecretStore
  target:
    name: license-token
    creationPolicy: Owner
    template:
      type: nginx.com/license
  data:
    - secretKey: license.jwt
      remoteRef:
        key: my-nginx-jwt-secret-id
