---
extends: default

# Don't impose these rules on copies of upstream packages
ignore:
  - packages/**/upstream*/**/*.yaml
  - packages/**/upstream*/**/*.yml

rules:
  line-length:
    max: 120
    ignore:
      # Embedded helm charts are longer than 120 chars
      - packages/**/helm-chart.yaml
      # Starlark sources often contain lines longer than 120 chars
      - packages/**/crd-remove-webhook.yaml
      - packages/**/label-cleanup.yaml
      - packages/**/secrets-sync-generator*.yaml
  document-start:
    # Kpt will remove leading '---' post-processing
    ignore:
      - packages/**/*.yaml
      - packages/**/Kptfile
  comments:
    # Kpt will reformat inline kpt-set to have a single space before comment
    ignore:
      - packages/**/*.yaml
  empty-lines:
    ignore:
      # Starlark source strings use empty lines for clarity
      - packages/**/crd-remove-webhook.yaml
      - packages/**/label-cleanup.yaml
      - packages/**/secrets-sync-generator*.yaml
