---
extends: default

# Upstream NGINX manifests shouldn't be linted
ignore:
  - applications/nic-crds/upstream/bases/*.yaml
  - applications/nic-oss/deployments/**/*.yaml
  - applications/nic-plus/deployments/**/*.yaml

rules:
  line-length:
    max: 120
  document-start:
    # Kpt will remove leading '---' post-processing
    ignore: |
      applications/**/*.yaml
      applications/**/Kptfile
