apiVersion: v1
kind: ConfigMap
metadata: # kpt-merge: nginx-ingress/nginx-config-mgmt
  name: nginx-config-mgmt
  namespace: nginx-ingress
  annotations:
    internal.kpt.dev/upstream-identifier: '|ConfigMap|nginx-ingress|nginx-config-mgmt'
data:
  license-token-secret-name: license-token
