apiVersion: fn.kpt.dev/v1alpha1
kind: RenderHelmChart
metadata:
  name: f5-ai-cai-scanner
helmCharts:
  - chartArgs:
      name: cai-scanner
      version: 2.4.0
      repo: oci://harbor.calypsoai.app/calypsoai
      auth:
        kind: Secret
        name: cai-harbor-credentials
    templateOptions:
      releaseName: cai-scanner
      namespace: f5-ai-scanner # kpt-set: ${cai-scanner-namespace}
      includeCRDs: false
      values:
        valuesInline:
          models:
            cai-phi-4-gptq-4bit:
              env:
                LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/nvidia/lib64
              image: harbor.calypsoai.app/calypsoai/cai_scanner:v2.4.0 # kpt-set: ${f5-ai-private-image-repository-prefix}harbor.calypsoai.app/calypsoai/cai_scanner:v2.4.0
              resourceProfile: nvidia-gpu-l4:1 # kpt-set: ${cai-scanner-model-resource-profile}
          enableModelHooks: false
          kubeai:
            # NOTE: These selectors ensure the cai-scanner (KubeAI) pods in an Autopilot GKE cluster get assigned to
            # nodes with more compute power than default Autopilot nodes. Change as needed, or for Standard GKE node
            # pool selection.
            nodeSelector:
              cloud.google.com/compute-class: Balanced
            crds:
              enabled: false
            # NOTE: An imagePullSecret is not needed when pulling from a private GAR repo with access managed through
            # IAM. Remove if relying on regcreds from upstream chart.
            imagePullSecrets: []
            image:
              repository: harbor.calypsoai.app/calypsoai/kubeai # kpt-set: ${f5-ai-private-image-repository-prefix}harbor.calypsoai.app/calypsoai/kubeai
            modelLoading:
              image: harbor.calypsoai.app/calypsoai/kubeai-model-loader:v0.14.0 # kpt-set: ${f5-ai-private-image-repository-prefix}harbor.calypsoai.app/calypsoai/kubeai-model-loader:v0.14.0
            # The values below are not directly exposed in upstream cai-scanner, but are in the included KubeAI
            # sub-chart and need to be changed if using a private registry.
            modelServers:
              VLLM:
                images:
                  default: vllm/vllm-openai:v0.10.2 # kpt-set: ${f5-ai-private-image-repository-prefix}vllm/vllm-openai:v0.10.2
                  nvidia-gpu: vllm/vllm-openai:v0.10.2 # kpt-set: ${f5-ai-private-image-repository-prefix}vllm/vllm-openai:v0.10.2
                  google-tpu: vllm-tpu:23194d83e8f2a6783b0d8c275f5f8a22faab9aec # kpt-set: ${f5-ai-private-image-repository-prefix}vllm-tpu:23194d83e8f2a6783b0d8c275f5f8a22faab9aec
                  gh200: vllm/vllm-openai:v0.10.2 # kpt-set: ${f5-ai-private-image-repository-prefix}vllm/vllm-openai:v0.10.2
            # Pull in the GKE resource profiles from sub-chart file kubeai/values-gke.yaml so that GKE ready profiles
            # are available for model selection above.
            # NOTE: The spot allocation strategy IS enabled by default for cai-scanner profiles because the cost
            # advantages make sense for demos and workshops where spot limitations make sense, but removal of the
            # gke-spot selector may be more suitable for production workloads where guaranteed availability is a
            # requirement. https://docs.cloud.google.com/kubernetes-engine/docs/concepts/spot-vms#overview
            resourceProfiles:
              nvidia-gpu-l4:
                nodeSelector:
                  cloud.google.com/gke-accelerator: nvidia-l4
                  cloud.google.com/gke-spot: "true"
              nvidia-gpu-h100:
                nodeSelector:
                  cloud.google.com/gke-accelerator: nvidia-h100-80gb
                  cloud.google.com/gke-spot: "true"
              nvidia-gpu-a100-80gb:
                nodeSelector:
                  cloud.google.com/gke-accelerator: nvidia-a100-80gb
                  cloud.google.com/gke-spot: "true"
              nvidia-gpu-a100-40gb:
                nodeSelector:
                  cloud.google.com/gke-accelerator: nvidia-tesla-a100
                  cloud.google.com/gke-spot: "true"
              google-tpu-v5e-1x1:
                imageName: google-tpu
                limits:
                  google.com/tpu: 1
                nodeSelector:
                  cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                  cloud.google.com/gke-tpu-topology: 1x1
                  cloud.google.com/gke-spot: "true"
              google-tpu-v5e-2x2:
                imageName: google-tpu
                limits:
                  google.com/tpu: 1
                nodeSelector:
                  cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                  cloud.google.com/gke-tpu-topology: 2x2
                  cloud.google.com/gke-spot: "true"
              google-tpu-v5e-2x4:
                imageName: google-tpu
                limits:
                  google.com/tpu: 1
                nodeSelector:
                  cloud.google.com/gke-tpu-accelerator: tpu-v5-lite-podslice
                  cloud.google.com/gke-tpu-topology: 2x4
                  cloud.google.com/gke-spot: "true"
            cacheProfiles:
              standard-filestore:
                sharedFilesystem:
                  storageClassName: "standard-rwx"
              premium-filestore:
                sharedFilesystem:
                  storageClassName: "premium-rwx"
