apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arcadia-llm-models
  namespace: arcadia-crypto
spec:
  resources:
    requests:
      storage: 5Gi
    limits:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arcadia-llm
  namespace: arcadia-crypto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arcadia-llm
  template:
    metadata:
      labels:
        app: arcadia-llm
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-t4  # kpt-set: ${gpu_type}
      containers:
        - name: arcadia-llm
          image: ollama/ollama@sha256:476b956cbe76f22494f08400757ba302fd8ab6573965c09f1e1a66b2a7b0eb77
          imagePullPolicy: IfNotPresent
          env:
            - name: OLLAMA_DEBUG
              value: "1"
          resources:
            limits:
              nvidia.com/gpu: 1  # kpt-set: ${gpu_count}
            requests:
              memory: 16384Mi
              cpu: 4000m
          ports:
            - containerPort: 11434
              protocol: TCP
          volumeMounts:
            - name: arcadia-llm-models
              mountPath: /root/.ollama/models
      volumes:
        - name: arcadia-llm-models
          persistentVolumeClaim:
            claimName: arcadia-llm-models
---
apiVersion: v1
kind: Service
metadata:
  name: arcadia-llm
  namespace: arcadia-crypto
spec:
  ports:
    - port: 11434
      targetPort: 11434
      protocol: TCP
      name: ollama
  selector:
    app: arcadia-llm
---
apiVersion: batch/v1
kind: Job
metadata:
  name: arcadia-llm-load-model
  namespace: arcadia-crypto
spec:
  ttlSecondsAfterFinished: 200
  template:
    spec:
      containers:
        - name: arcadia-llm-load-llama3b8b
          image: ollama/ollama@sha256:476b956cbe76f22494f08400757ba302fd8ab6573965c09f1e1a66b2a7b0eb77
          command:
            - ollama
            - pull
            - llama3.1:8b
          env:
            - name: OLLAMA_HOST
              value: arcadia-llm:11434
      restartPolicy: Never
