apiVersion: v1
kind: ConfigMap
metadata:
  name: config-helm-upgrader
data:
  annotateOnUpgradeAvailable: true
  annotateSumOnUpgradeAvailable: true
  upgradeOnUpgradeAvailable: false
  annotateCurrentSum: true
