apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cai-workflows-auth
  namespace: f5-ai-redteam
spec:
  provider: gke
  parameters:
    secrets: "" # NOTE: This will be populated by secret-sync-generator pipeline component.
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: cai-workflows-auth
  namespace: f5-ai-redteam
spec:
  serviceAccountName: default
  secretProviderClassName: cai-workflows-auth
  secretObject:
    type: Opaque
    data: [] # NOTE: This will be populated by secret-sync-generator pipeline component.
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: prefect-server-auth
  namespace: f5-ai-redteam
spec:
  provider: gke
  parameters:
    secrets: "" # NOTE: This will be populated by secret-sync-generator pipeline component.
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: prefect-server-auth
  namespace: f5-ai-redteam
spec:
  serviceAccountName: prefect-server
  secretProviderClassName: prefect-server-auth
  secretObject:
    type: Opaque
    data: [] # NOTE: This will be populated by secret-sync-generator pipeline component.
