apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: cai-moderator
  namespace: f5-ai-moderator
spec:
  parentRefs:
    - name: cluster-gw # kpt-set: ${shared-gateway-name}
      namespace: shared-services # kpt-set: ${shared-gateway-namespace}
      sectionName: f5-ai # kpt-set: ${shared-gateway-listener-name}
  rules:
    - name: auth
      matches:
        - path:
            type: PathPrefix
            value: /auth
      backendRefs:
        - name: cai-moderator
          port: 8080
    - name: default
      matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: cai-moderator
          port: 5500
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: cai-moderator
  namespace: f5-ai-moderator
spec:
  default:
    checkIntervalSec: 15
    timeoutSec: 10
    healthyThreshold: 1
    unhealthyThreshold: 3
    logConfig:
      enabled: false
    config:
      type: HTTP
      httpHealthCheck:
        port: 5500
        requestPath: /
  targetRef:
    group: ""
    kind: Service
    name: cai-moderator
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: f5-ai-moderator
  namespace: f5-ai-moderator
spec:
  default:
    securityPolicy: f5-ai-cloud-armor-security-policy # kpt-set: ${cai-moderator-cloud-armor-security-policy}
  targetRef:
    group: ""
    kind: Service
    name: cai-moderator
