apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cai-moderator-auth
  namespace: f5-ai-moderator
spec:
  provider: gke
  parameters:
    secrets: "" # NOTE: This will be populated by secret-sync-generator pipeline component.
---
apiVersion: secret-sync.gke.io/v1
kind: SecretSync
metadata:
  name: cai-moderator-auth
  namespace: f5-ai-moderator
spec:
  serviceAccountName: cai-moderator-sa
  secretProviderClassName: cai-moderator-auth
  secretObject:
    type: Opaque
    data: [] # NOTE: This will be populated by secret-sync-generator pipeline component.
