apiVersion: fn.kpt.dev/v1alpha1
kind: StarlarkRun
metadata:
  name: secrets-sync-generator
  annotations:
    config.kubernetes.io/local-config: "true"
params:
  # The fully-qualified Secret Manager secret id AND version that contains a JSON secret with the fields listed below.
  secret_id: projects/PROJECT_ID/secrets/SECRET_ID/versions/latest # kpt-set: ${cai-moderator-auth-secret-id}/versions/latest
  # The name assigned to the SecretProviderClass resource that will be refreshed by this script.
  secret_provider_class_name: cai-moderator-auth
  # The name assigned to the SecretSync resource that will be refreshed by this script.
  # NOTE: This can be an empty string if SecretSync injection is not used, e.g. if CSI volume is mounted for pod.
  secret_sync_name: cai-moderator-auth
  # The list of JSON fields to expose in the CSI volume and Kubernetes secret.
  fields:
    - CAI_MODERATOR_AUTH_IDP_CLIENT_ID
    - CAI_MODERATOR_AUTH_IDP_CLIENT_SECRET
    - CAI_MODERATOR_AUTH_IDP_ISSUER
    - CAI_MODERATOR_DB_ADMIN_PASSWORD
    - CAI_MODERATOR_DB_MODERATOR_PASSWORD
    - CAI_MODERATOR_DEFAULT_LICENSE
    - CAI_MODERATOR_EMAIL_PASSWORD
    - CAI_MODERATOR_EMAIL_USER
    - CAI_MODERATOR_JOB_MANAGER_ENCRYPTION_KEY
# This starlark script will generate the parameters expected by Secrets Store CSI driver and GKE SecretSync resources
# from the list of fields.
source: |
  load('encoding/yaml.star', 'yaml')

  def secretStoreCSIEntry(secret_id, field):
    return {
      "resourceName": secret_id,
      "path": ".%s" % field,
      "extractJSONKey": field,
    }

  def secretSyncEntry(field):
    return {
      "sourcePath": ".%s" % field,
      "targetKey": field,
    }

  secret_provider_class_name_to_match = ctx.resource_list["functionConfig"]["params"]["secret_provider_class_name"]
  secret_sync_name_to_match = ctx.resource_list["functionConfig"]["params"].get("secret_sync_name", None)
  secret_id = ctx.resource_list["functionConfig"]["params"]["secret_id"]
  fields = ctx.resource_list["functionConfig"]["params"]["fields"]
  for resource in ctx.resource_list["items"]:
    if resource["apiVersion"] == "secrets-store.csi.x-k8s.io/v1" and resource["kind"] == "SecretProviderClass" and resource["metadata"]["name"] == secret_provider_class_name_to_match:
      resource["spec"]["parameters"]["secrets"] = yaml.dumps([secretStoreCSIEntry(secret_id, field) for field in fields])
    if secret_sync_name_to_match and resource["apiVersion"] == "secret-sync.gke.io/v1" and resource["kind"] == "SecretSync" and resource["metadata"]["name"] == secret_sync_name_to_match:
      resource["spec"]["secretObject"]["data"] = [secretSyncEntry(field) for field in fields]
